### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Gavinwilk** [narbs91/glosseta#80]
### What happened?

A bug happened!

### How to reproduce the bug?

2. Click on '...'
3. Scroll down to '...'

### What browsers are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device type(s) did you see the problem on?

- [X] Desktop
- [X] Mobile
- [ ] Tablet

### What operating system(s) did you see the problem on?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional information

King von

**Comment by narbs91** [comment]
Hi @Gavinwilk thanks for creating a bug ticket; however, there isn't enough context here for me to understand what the actual issue is.  Could you please help me understand the situation by providing more information around what the bug is, how you produced it and what you expected to happen (versus what actually did)?

**Comment by narbs91** [comment]
Going to close this bug out as no further context has been provided for investigation
